"clickhouse":
  "hosts":
    "clickhouse-01":
      "ansible_host": "89.169.148.248"
      "ansible_user": "almalinux"
"vector":
  "hosts":
    "vector-01":
      "ansible_host": "111.88.245.65"
      "ansible_user": "almalinux"
